apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfsshare
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /nfsshare
    server: 172.16.99.56
